class_list = [(0, "Flagship"), (1, "Probe"), (2, "Medium-class Explorer (MIDEX)"), (3, "Small Explorer (SMEX)")]
location_list = [(0, "Near Earth Orbit [Hubble]"), (1, "L2 [JWST]"), (2, "Other Solar System Orbit [Spitzer]"), (3, "The Moon [Artemis]"), (4, "Outside of the Solar System [Voyager]")]
wavelength_list = [(0, "Gamma Ray"), (1, "X-Ray"), (2, "UV"), (3, "Visible"), (4, "Infrared"), (5, "Microwave/Sub-millimeter"), (6, "Radio")]
design_list = [(0, "Standard tube [Hubble]"), (1, "Open mirror plus sun shield [JWST]")]
optics_list = [(0, "Standard mirror [Hubble]"), (1, "Segmented mirror [JWST]"), (2, "Parabolic grazing incidence mirror [Chandra]"), (3, "No Mirror [Fermi]")]
fov_list = [(0, "Narrow [Hubble]"), (1, "Wide [Roman]")]
instrument_list = [(0, "Imager (camera)"), (1, "Photometers"), (2, "Spectrographs"), (3, "Polarimeters")]
extras_list = [(0, "None"), (1, "Coronograph"), (2, "Starshade")]